server:
  port: 80
  
spring:
  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
        
zuul:
  force-original-query-string-encoding: true