server:
  port: 1000
spring:
  application:
    name: upms
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver